baseURL = "https://lively-bay-0e10f701e.2.azurestaticapps.net/"
languageCode = "en-us"
title = "Deepwater Technologies"
theme = "timer"
# post pagination
paginate = "2" # see https://gohugo.io/extras/pagination/

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "Home"
url = "/"
weight = 1
color = "white"

[[menu.main]]
name = "About"
pre = "#"
url = "about"
weight = 2

[[menu.main]]
name = "What I do"
pre = "#"
url = "wid"
weight = 3

[[menu.main]]
name = "Projects"
pre = "#"
url = "works"
weight = 4

[[menu.main]]
name = "Contact"
pre = "#"
url = "call-to-action" 
weight = 5
# Site Params
[params]
home = "Home"
logo = "img/DTnavyhorizontal.png"
dateFormat = "6 January 2006"
# Meta data
description = "Deepwater Technologies"
author = "Themefisher" 
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable = true
bgImage = "img/20210430_124538540_iOS.jpg" 
heading = "HI, MY NAME IS DAN & I AM A"
description = "I CREATE CUSTOM SOFTWARE APPLICATIONS FOR SMALL TO MEDIUM-SIZED BUSINESSES THAT AUTOMATE REPETITIVE, MANUAL TASKS, IMPROVE WORKFLOW, AND INCREASE ACCURACY THAT GIVES YOU  TIME BACK TO FOCUS ON WHAT IS REALLY IMPORTANT TO YOU, RUNNING YOUR BUSINESS."
# button
btn = false

# flip text
[[params.banner.flipText]]
title = "DEVELOPER"
[[params.banner.flipText]]
title = "LISTENER"
[[params.banner.flipText]]
title = "PROBLEM SOLVER"
[[params.banner.flipText]]
title = "SANITY SAVER"
[[params.banner.flipText]]
title = "TIME GENERATOR"

# Homepage About Section
[params.about]
enable = true
title = "ABOUT ME"
content = "I've spent the last 25 years building custom business applications for large and small businesses around the northwest. I now live in Wenatchee WA and really enjoy working directly with the people who will use the software I build. Building something that gives you more time to spend on your business priorities, is what itâ€™s all about."
image = "img/20230119_213110067_iOS.jpg" 

# Call to Action
[params.cta]
enable = true
title = "IF YOUR LOOKING TO GENERATE SOME TIME, PERHAPS I CAN HELP."
content = ""
linkPhoneText = "509-881-8762"
linkPhone = "5098818762"
linkEmailText = "dan@deepwatertechnologies.com"
linkEmail = "mailto:dan@deepwatertechnologies.com"

[params.wid]
enable = true

# Portfolio Section On Homepage
[params.portfolio]
enable = true
title = "Projects"
subtitle = "Want a little more detail or perhaps some street cred. Here are a few examples of my work."

# social icon
[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "https://www.linkedin.com/in/daniel-kjobech-8a49048/"
