baseURL = "https://lively-bay-0e10f701e.2.azurestaticapps.net/"
languageCode = "en-us"
title = "Deepwater Technologies"
theme = "timer"
# post pagination
paginate = "2" # see https://gohugo.io/extras/pagination/

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "Home"
url = "/"
weight = 1
color = "white"

[[menu.main]]
name = "About"
pre = "#"
url = "about"
weight = 2

[[menu.main]]
name = "Services"
pre = "#"
url = "works"
weight = 3

[[menu.main]]
name = "Contact"
pre = "#"
url = "call-to-action" 
weight = 6

# Site Params
[params]
home = "Home"
logo = "img/DTnavyhorizontal.png"
dateFormat = "6 January 2006"
# Meta data
description = "Deepwater Technologies"
author = "Themefisher" 
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable = true
bgImage = "img/lake-large-small.jpg" 
heading = "HI, MY NAME IS DAN & I AM A"
description = "WITH MORE THAN 250 YEARS EXPERIENCE, I'VE BUILT CUSTOM SOFTWARE FOR LARGE AND SMALL COMPANIES ALIKE. I BRING WIDELEY VARIED EXPERIENCE TO HELP YOU TAKE BACK TIME TO FOCUS ON WHAT IS REALLY IMPORTANT TO YOU, RUNNING YOUR BUSINESS."
# button
btn = false

# flip text
[[params.banner.flipText]]
title = "DEVELOPER"
[[params.banner.flipText]]
title = "LISTENER"
[[params.banner.flipText]]
title = "PROBLEM SOLVER"
[[params.banner.flipText]]
title = "SANITY SAVER"
[[params.banner.flipText]]
title = "TIME GENERATOR"

# Homepage About Section
[params.about]
enable = true
title = "ABOUT ME"
content = "Hello, I've spent the last 25 years building custom business applications for large and small businesses around the northwest. I now live in Wenatchee WA, and really enjoy working with small to medium-sized businesses where I get to meet the people who will use the software I build. Working with them to build something that makes their work life MUCH easier is what it’s all about.<br><br>When I say 'take back time', it really is true. We all have repetitive, necessary tasks that are part of running our business and these can often be very manual and time-consuming.  Making software that allows a computer to handle those tasks literally gives you time back to focus on your priorities.<br><br>I like to work closely with my customers. It starts with discussions about how your business operates,  identifying key processes, presenting solutions, and iterating on those ideas until you like what you see. Once the design is complete, we start building.  I regularly release new versions so you can see, click, and assess the software. You are along for the ride every step of the way, not just getting postcards in the mail.<br><br>Finally, in our world, things change, sometimes very quickly. I'm here for you. I can update your software as needs change in a timely manner. I’m a real person just a phone call away."
image = "img/20230119_213110067_iOS.jpg" 

# Call to Action
[params.cta]
enable = true
title = "IF YOUR LOOKING TO GENERATE SOME TIME, PERHAPS I CAN HELP:"
content = ""
linkPhoneText = "509-881-8762"
linkPhone = "5098818762"
linkEmailText = "dan@deepwatertechnologies.com"
linkEmail = "mailto:dan@deepwatertechnologies.com"

# Portfolio Section On Homepage
[params.portfolio]
enable = true
title = "WHAT I DO"
subtitle = "Instead of me trying to explain it, why don’t I tell you a few stories of people I’ve helped."

[params.service]
enable = true
title = "services stuff"

# social icon
[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "https://www.linkedin.com/in/daniel-kjobech-8a49048/"
